/* ============================================================
   Klima-Rezepte — Lebensmittel- und Referenzwert-Datenbank
   Basis: CO2-Rucksack-Lebensmittel.xlsx (Poore & Nemecek 2018 / OWID,
   ifeu Heidelberg 2013 Fleisch- & Gemüse-Bericht, Thünen-Institut,
   Alcock et al. 2022). co2 = kg CO2e je kg, Deutschland-/Saisonbasis.
   Nährwerte je 100 g. Stand: 11.09.2026.
   ============================================================ */

const FOODS = [
  {
    "name": "Rindfleisch",
    "co2": 14.0,
    "season": "ganzjährig (Tierhaltung)",
    "kcal": 250,
    "fett": 15,
    "eiweiss": 26,
    "kh": 0,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 0.3,
    "vitK": 1.5,
    "b1": 0.08,
    "b2": 0.2,
    "niacin": 5.0,
    "b6": 0.4,
    "folat": 6,
    "b12": 2.5,
    "ca": 12,
    "fe": 2.5,
    "mg": 22,
    "zn": 4.5,
    "k": 350
  },
  {
    "name": "Lammfleisch",
    "co2": 39.72,
    "season": "ganzjährig",
    "kcal": 250,
    "fett": 17,
    "eiweiss": 25,
    "kh": 0,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0.1,
    "vitE": 0.5,
    "vitK": 4.0,
    "b1": 0.1,
    "b2": 0.23,
    "niacin": 6.0,
    "b6": 0.15,
    "folat": 5,
    "b12": 2.6,
    "ca": 8,
    "fe": 1.9,
    "mg": 21,
    "zn": 4.0,
    "k": 310
  },
  {
    "name": "Schweinefleisch",
    "co2": 5.0,
    "season": "ganzjährig (Tierhaltung)",
    "kcal": 242,
    "fett": 17,
    "eiweiss": 21,
    "kh": 0,
    "vitA": 2,
    "vitC": 0.5,
    "vitD": 1.0,
    "vitE": 0.3,
    "vitK": 0,
    "b1": 0.6,
    "b2": 0.2,
    "niacin": 5.0,
    "b6": 0.5,
    "folat": 3,
    "b12": 0.7,
    "ca": 10,
    "fe": 0.9,
    "mg": 20,
    "zn": 2.0,
    "k": 380
  },
  {
    "name": "Hähnchenfleisch",
    "co2": 9.87,
    "season": "ganzjährig",
    "kcal": 165,
    "fett": 3.5,
    "eiweiss": 31,
    "kh": 0,
    "vitA": 6,
    "vitC": 0,
    "vitD": 0.1,
    "vitE": 0.3,
    "vitK": 0,
    "b1": 0.07,
    "b2": 0.1,
    "niacin": 10.0,
    "b6": 0.6,
    "folat": 4,
    "b12": 0.3,
    "ca": 11,
    "fe": 0.7,
    "mg": 25,
    "zn": 1.0,
    "k": 250
  },
  {
    "name": "Lachs (Zucht)",
    "co2": 13.63,
    "season": "ganzjährig (Aquakultur, Import)",
    "kcal": 208,
    "fett": 13,
    "eiweiss": 20,
    "kh": 0,
    "vitA": 12,
    "vitC": 0,
    "vitD": 11.0,
    "vitE": 3.5,
    "vitK": 0.1,
    "b1": 0.2,
    "b2": 0.4,
    "niacin": 8.0,
    "b6": 0.6,
    "folat": 26,
    "b12": 3.2,
    "ca": 12,
    "fe": 0.5,
    "mg": 27,
    "zn": 0.6,
    "k": 380
  },
  {
    "name": "Garnelen (Zucht)",
    "co2": 26.87,
    "season": "ganzjährig (Aquakultur, Import)",
    "kcal": 85,
    "fett": 0.5,
    "eiweiss": 20,
    "kh": 0,
    "vitA": 0,
    "vitC": 2.0,
    "vitD": 0,
    "vitE": 1.0,
    "vitK": 0,
    "b1": 0.02,
    "b2": 0.03,
    "niacin": 2.0,
    "b6": 0.1,
    "folat": 3,
    "b12": 1.2,
    "ca": 70,
    "fe": 0.5,
    "mg": 40,
    "zn": 1.3,
    "k": 260
  },
  {
    "name": "Eier",
    "co2": 4.67,
    "season": "ganzjährig",
    "kcal": 155,
    "fett": 11,
    "eiweiss": 13,
    "kh": 1.1,
    "vitA": 160,
    "vitC": 0,
    "vitD": 2.0,
    "vitE": 1.0,
    "vitK": 0.3,
    "b1": 0.07,
    "b2": 0.5,
    "niacin": 0.1,
    "b6": 0.17,
    "folat": 47,
    "b12": 0.9,
    "ca": 50,
    "fe": 1.8,
    "mg": 12,
    "zn": 1.3,
    "k": 140
  },
  {
    "name": "Kuhmilch",
    "co2": 1.3,
    "season": "ganzjährig (Tierhaltung)",
    "kcal": 64,
    "fett": 3.5,
    "eiweiss": 3.3,
    "kh": 4.8,
    "vitA": 28,
    "vitC": 1.0,
    "vitD": 0.1,
    "vitE": 0.1,
    "vitK": 0.2,
    "b1": 0.04,
    "b2": 0.18,
    "niacin": 0.1,
    "b6": 0.04,
    "folat": 5,
    "b12": 0.4,
    "ca": 120,
    "fe": 0.05,
    "mg": 12,
    "zn": 0.4,
    "k": 150
  },
  {
    "name": "Käse (Hartkäse)",
    "co2": 9.8,
    "season": "ganzjährig (Tierhaltung)",
    "kcal": 350,
    "fett": 28,
    "eiweiss": 25,
    "kh": 2.0,
    "vitA": 200,
    "vitC": 0,
    "vitD": 0.5,
    "vitE": 0.5,
    "vitK": 2.0,
    "b1": 0.03,
    "b2": 0.35,
    "niacin": 0.1,
    "b6": 0.08,
    "folat": 20,
    "b12": 1.5,
    "ca": 800,
    "fe": 0.3,
    "mg": 30,
    "zn": 3.5,
    "k": 100
  },
  {
    "name": "Tofu",
    "co2": 3.16,
    "season": "ganzjährig",
    "kcal": 145,
    "fett": 9,
    "eiweiss": 15,
    "kh": 3.0,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 0.1,
    "vitK": 2.0,
    "b1": 0.08,
    "b2": 0.05,
    "niacin": 0.2,
    "b6": 0.05,
    "folat": 15,
    "b12": 0,
    "ca": 200,
    "fe": 2.7,
    "mg": 30,
    "zn": 1.0,
    "k": 150
  },
  {
    "name": "Sojamilch",
    "co2": 0.98,
    "season": "ganzjährig",
    "kcal": 40,
    "fett": 2.0,
    "eiweiss": 3.3,
    "kh": 1.0,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 0.5,
    "vitK": 3.0,
    "b1": 0.03,
    "b2": 0.02,
    "niacin": 0.2,
    "b6": 0.05,
    "folat": 3,
    "b12": 0,
    "ca": 13,
    "fe": 0.6,
    "mg": 19,
    "zn": 0.3,
    "k": 150
  },
  {
    "name": "Erdnüsse",
    "co2": 3.23,
    "season": "keine dt. Erzeugung (Import)",
    "kcal": 570,
    "fett": 49,
    "eiweiss": 26,
    "kh": 16,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 8.0,
    "vitK": 0,
    "b1": 0.6,
    "b2": 0.1,
    "niacin": 12.0,
    "b6": 0.35,
    "folat": 240,
    "b12": 0,
    "ca": 92,
    "fe": 4.6,
    "mg": 168,
    "zn": 3.3,
    "k": 700
  },
  {
    "name": "Mandeln",
    "co2": 0.43,
    "season": "ganzjährig",
    "kcal": 580,
    "fett": 50,
    "eiweiss": 21,
    "kh": 22,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 25.0,
    "vitK": 0,
    "b1": 0.2,
    "b2": 1.1,
    "niacin": 3.6,
    "b6": 0.1,
    "folat": 50,
    "b12": 0,
    "ca": 260,
    "fe": 3.7,
    "mg": 270,
    "zn": 3.1,
    "k": 730
  },
  {
    "name": "Linsen (trocken)",
    "co2": 1.79,
    "season": "ganzjährig",
    "kcal": 325,
    "fett": 1.5,
    "eiweiss": 24,
    "kh": 52,
    "vitA": 0,
    "vitC": 2.0,
    "vitD": 0,
    "vitE": 0.5,
    "vitK": 5.0,
    "b1": 0.5,
    "b2": 0.25,
    "niacin": 2.5,
    "b6": 0.5,
    "folat": 480,
    "b12": 0,
    "ca": 50,
    "fe": 7.5,
    "mg": 90,
    "zn": 3.5,
    "k": 950
  },
  {
    "name": "Erbsen (TK, gegart)",
    "co2": 0.98,
    "season": "ganzjährig",
    "kcal": 80,
    "fett": 0.4,
    "eiweiss": 5.0,
    "kh": 14,
    "vitA": 38,
    "vitC": 15,
    "vitD": 0,
    "vitE": 0.1,
    "vitK": 25,
    "b1": 0.15,
    "b2": 0.1,
    "niacin": 1.5,
    "b6": 0.1,
    "folat": 30,
    "b12": 0,
    "ca": 25,
    "fe": 1.5,
    "mg": 33,
    "zn": 1.2,
    "k": 240
  },
  {
    "name": "Reis (roh)",
    "co2": 4.45,
    "season": "keine dt. Erzeugung (Import)",
    "kcal": 360,
    "fett": 0.7,
    "eiweiss": 7.0,
    "kh": 79,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 0.1,
    "vitK": 0,
    "b1": 0.07,
    "b2": 0.05,
    "niacin": 1.6,
    "b6": 0.16,
    "folat": 8,
    "b12": 0,
    "ca": 10,
    "fe": 0.8,
    "mg": 25,
    "zn": 1.1,
    "k": 76
  },
  {
    "name": "Haferflocken",
    "co2": 2.48,
    "season": "ganzjährig",
    "kcal": 370,
    "fett": 7.0,
    "eiweiss": 13,
    "kh": 60,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 0.4,
    "vitK": 0,
    "b1": 0.5,
    "b2": 0.1,
    "niacin": 1.0,
    "b6": 0.1,
    "folat": 30,
    "b12": 0,
    "ca": 55,
    "fe": 4.5,
    "mg": 130,
    "zn": 3.6,
    "k": 400
  },
  {
    "name": "Weizenbrot",
    "co2": 1.57,
    "season": "ganzjährig",
    "kcal": 250,
    "fett": 1.5,
    "eiweiss": 8.0,
    "kh": 50,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 0.3,
    "vitK": 0,
    "b1": 0.15,
    "b2": 0.08,
    "niacin": 1.5,
    "b6": 0.06,
    "folat": 30,
    "b12": 0,
    "ca": 30,
    "fe": 1.8,
    "mg": 25,
    "zn": 0.7,
    "k": 130
  },
  {
    "name": "Mais (Zuckermais, TK/Dose)",
    "co2": 1.7,
    "season": "ganzjährig",
    "kcal": 96,
    "fett": 1.5,
    "eiweiss": 3.4,
    "kh": 21,
    "vitA": 10,
    "vitC": 7.0,
    "vitD": 0,
    "vitE": 0.1,
    "vitK": 0.3,
    "b1": 0.15,
    "b2": 0.06,
    "niacin": 1.5,
    "b6": 0.06,
    "folat": 40,
    "b12": 0,
    "ca": 2,
    "fe": 0.5,
    "mg": 26,
    "zn": 0.5,
    "k": 270
  },
  {
    "name": "Gerste (roh)",
    "co2": 1.18,
    "season": "ganzjährig",
    "kcal": 354,
    "fett": 1.2,
    "eiweiss": 9.9,
    "kh": 73,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 0.1,
    "vitK": 0,
    "b1": 0.19,
    "b2": 0.11,
    "niacin": 4.6,
    "b6": 0.26,
    "folat": 23,
    "b12": 0,
    "ca": 29,
    "fe": 2.5,
    "mg": 79,
    "zn": 2.1,
    "k": 280
  },
  {
    "name": "Kartoffeln (roh)",
    "co2": 0.46,
    "season": "Ernte Aug–Okt, ganzjährig aus Lager",
    "kcal": 70,
    "fett": 0.1,
    "eiweiss": 1.9,
    "kh": 16,
    "vitA": 0,
    "vitC": 20,
    "vitD": 0,
    "vitE": 0,
    "vitK": 2.0,
    "b1": 0.1,
    "b2": 0.03,
    "niacin": 1.1,
    "b6": 0.3,
    "folat": 16,
    "b12": 0,
    "ca": 8,
    "fe": 0.5,
    "mg": 21,
    "zn": 0.3,
    "k": 420
  },
  {
    "name": "Zwiebeln",
    "co2": 0.5,
    "season": "Ernte Aug–Sept, ganzjährig aus Lager",
    "kcal": 40,
    "fett": 0.1,
    "eiweiss": 1.1,
    "kh": 9.0,
    "vitA": 0,
    "vitC": 7.0,
    "vitD": 0,
    "vitE": 0,
    "vitK": 0.4,
    "b1": 0.05,
    "b2": 0.02,
    "niacin": 0.1,
    "b6": 0.12,
    "folat": 19,
    "b12": 0,
    "ca": 23,
    "fe": 0.2,
    "mg": 10,
    "zn": 0.2,
    "k": 150
  },
  {
    "name": "Brokkoli",
    "co2": 0.51,
    "season": "Freiland: Juni–November",
    "kcal": 34,
    "fett": 0.4,
    "eiweiss": 2.8,
    "kh": 7.0,
    "vitA": 31,
    "vitC": 89,
    "vitD": 0,
    "vitE": 0.8,
    "vitK": 102,
    "b1": 0.07,
    "b2": 0.12,
    "niacin": 0.6,
    "b6": 0.2,
    "folat": 63,
    "b12": 0,
    "ca": 47,
    "fe": 0.7,
    "mg": 21,
    "zn": 0.4,
    "k": 316
  },
  {
    "name": "Karotten",
    "co2": 0.43,
    "season": "ganzjährig (Freiland + Lager)",
    "kcal": 41,
    "fett": 0.2,
    "eiweiss": 0.9,
    "kh": 10,
    "vitA": 835,
    "vitC": 6.0,
    "vitD": 0,
    "vitE": 0.7,
    "vitK": 13,
    "b1": 0.07,
    "b2": 0.06,
    "niacin": 1.0,
    "b6": 0.1,
    "folat": 19,
    "b12": 0,
    "ca": 33,
    "fe": 0.3,
    "mg": 12,
    "zn": 0.2,
    "k": 320
  },
  {
    "name": "Paprika (rot)",
    "co2": 0.53,
    "season": "Freiland/Folientunnel: Juli–Oktober",
    "kcal": 31,
    "fett": 0.3,
    "eiweiss": 1.0,
    "kh": 6.0,
    "vitA": 157,
    "vitC": 128,
    "vitD": 0,
    "vitE": 1.6,
    "vitK": 4.9,
    "b1": 0.05,
    "b2": 0.09,
    "niacin": 1.2,
    "b6": 0.3,
    "folat": 46,
    "b12": 0,
    "ca": 7,
    "fe": 0.4,
    "mg": 12,
    "zn": 0.3,
    "k": 210
  },
  {
    "name": "Äpfel",
    "co2": 0.43,
    "season": "Ernte Sept–Nov, ganzjährig aus Kühllager",
    "kcal": 52,
    "fett": 0.2,
    "eiweiss": 0.3,
    "kh": 14,
    "vitA": 3,
    "vitC": 5.0,
    "vitD": 0,
    "vitE": 0.2,
    "vitK": 2.2,
    "b1": 0.02,
    "b2": 0.02,
    "niacin": 0.1,
    "b6": 0.04,
    "folat": 3,
    "b12": 0,
    "ca": 6,
    "fe": 0.1,
    "mg": 5,
    "zn": 0.04,
    "k": 110
  },
  {
    "name": "Bananen",
    "co2": 0.86,
    "season": "keine dt. Erzeugung (Import)",
    "kcal": 89,
    "fett": 0.3,
    "eiweiss": 1.1,
    "kh": 23,
    "vitA": 3,
    "vitC": 9.0,
    "vitD": 0,
    "vitE": 0.1,
    "vitK": 0.5,
    "b1": 0.03,
    "b2": 0.07,
    "niacin": 0.7,
    "b6": 0.4,
    "folat": 20,
    "b12": 0,
    "ca": 5,
    "fe": 0.3,
    "mg": 27,
    "zn": 0.15,
    "k": 360
  },
  {
    "name": "Orangen",
    "co2": 0.39,
    "season": "keine dt. Erzeugung (Import)",
    "kcal": 47,
    "fett": 0.1,
    "eiweiss": 0.9,
    "kh": 12,
    "vitA": 11,
    "vitC": 53,
    "vitD": 0,
    "vitE": 0.2,
    "vitK": 0,
    "b1": 0.09,
    "b2": 0.04,
    "niacin": 0.3,
    "b6": 0.06,
    "folat": 30,
    "b12": 0,
    "ca": 40,
    "fe": 0.1,
    "mg": 10,
    "zn": 0.07,
    "k": 180
  },
  {
    "name": "Weintrauben",
    "co2": 1.53,
    "season": "in D kaum kommerziell angebaut",
    "kcal": 69,
    "fett": 0.2,
    "eiweiss": 0.7,
    "kh": 18,
    "vitA": 3,
    "vitC": 4.0,
    "vitD": 0,
    "vitE": 0.2,
    "vitK": 14.6,
    "b1": 0.07,
    "b2": 0.07,
    "niacin": 0.2,
    "b6": 0.09,
    "folat": 2,
    "b12": 0,
    "ca": 10,
    "fe": 0.4,
    "mg": 7,
    "zn": 0.07,
    "k": 190
  },
  {
    "name": "Zucker (Rübenzucker)",
    "co2": 1.81,
    "season": "ganzjährig",
    "kcal": 400,
    "fett": 0,
    "eiweiss": 0,
    "kh": 100,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 0,
    "vitK": 0,
    "b1": 0,
    "b2": 0,
    "niacin": 0,
    "b6": 0,
    "folat": 0,
    "b12": 0,
    "ca": 1,
    "fe": 0.01,
    "mg": 0,
    "zn": 0,
    "k": 2
  },
  {
    "name": "Kaffee (geröstet, trocken)",
    "co2": 28.53,
    "season": "keine dt. Erzeugung (Import)",
    "kcal": 331,
    "fett": 21,
    "eiweiss": 14,
    "kh": 0,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 0,
    "vitK": 0,
    "b1": 0.01,
    "b2": 0.2,
    "niacin": 14.0,
    "b6": 0.03,
    "folat": 0,
    "b12": 0,
    "ca": 140,
    "fe": 4.0,
    "mg": 170,
    "zn": 0.5,
    "k": 2000
  },
  {
    "name": "Zartbitterschokolade",
    "co2": 46.65,
    "season": "ganzjährig",
    "kcal": 550,
    "fett": 38,
    "eiweiss": 6.0,
    "kh": 45,
    "vitA": 3,
    "vitC": 0,
    "vitD": 0,
    "vitE": 0.6,
    "vitK": 6.0,
    "b1": 0.03,
    "b2": 0.08,
    "niacin": 1.0,
    "b6": 0.04,
    "folat": 8,
    "b12": 0.3,
    "ca": 60,
    "fe": 8.0,
    "mg": 150,
    "zn": 2.0,
    "k": 600
  },
  {
    "name": "Wein (Rotwein)",
    "co2": 1.79,
    "season": "ganzjährig",
    "kcal": 85,
    "fett": 0,
    "eiweiss": 0.1,
    "kh": 2.6,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 0,
    "vitK": 0,
    "b1": 0,
    "b2": 0.01,
    "niacin": 0.1,
    "b6": 0.03,
    "folat": 2,
    "b12": 0,
    "ca": 8,
    "fe": 0.5,
    "mg": 10,
    "zn": 0.1,
    "k": 100
  },
  {
    "name": "Rapsöl",
    "co2": 2.49,
    "season": "ganzjährig",
    "kcal": 828,
    "fett": 92,
    "eiweiss": 0,
    "kh": 0,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 17.0,
    "vitK": 71,
    "b1": 0,
    "b2": 0,
    "niacin": 0,
    "b6": 0,
    "folat": 0,
    "b12": 0,
    "ca": 0,
    "fe": 0,
    "mg": 0,
    "zn": 0,
    "k": 0
  },
  {
    "name": "Nudeln (Vollkorn, trocken)",
    "co2": 1.57,
    "season": "ganzjährig",
    "kcal": 350,
    "fett": 1.5,
    "eiweiss": 12.5,
    "kh": 70,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 0.2,
    "vitK": 1.0,
    "b1": 0.15,
    "b2": 0.06,
    "niacin": 2.0,
    "b6": 0.1,
    "folat": 20,
    "b12": 0,
    "ca": 20,
    "fe": 1.5,
    "mg": 45,
    "zn": 1.3,
    "k": 190
  },
  {
    "name": "Tomaten (regional, beheiztes Gewächshaus)",
    "co2": 3.0,
    "season": "ganzjährig (Mitte März – Mitte Dezember)",
    "kcal": 18,
    "fett": 0.2,
    "eiweiss": 0.9,
    "kh": 3.9,
    "vitA": 42,
    "vitC": 14,
    "vitD": 0,
    "vitE": 0.5,
    "vitK": 8.0,
    "b1": 0.04,
    "b2": 0.02,
    "niacin": 0.6,
    "b6": 0.08,
    "folat": 15,
    "b12": 0,
    "ca": 10,
    "fe": 0.3,
    "mg": 11,
    "zn": 0.2,
    "k": 240
  },
  {
    "name": "Tomaten (regional, unbeheizter Folientunnel)",
    "co2": 0.7,
    "season": "Anfang Juni – Mitte Oktober",
    "kcal": 18,
    "fett": 0.2,
    "eiweiss": 0.9,
    "kh": 3.9,
    "vitA": 42,
    "vitC": 14,
    "vitD": 0,
    "vitE": 0.5,
    "vitK": 8.0,
    "b1": 0.04,
    "b2": 0.02,
    "niacin": 0.6,
    "b6": 0.08,
    "folat": 15,
    "b12": 0,
    "ca": 10,
    "fe": 0.3,
    "mg": 11,
    "zn": 0.2,
    "k": 240
  },
  {
    "name": "Tomaten (Import Südspanien, unbeheizt)",
    "co2": 0.4,
    "season": "ganzjährig verfügbar (v.a. Winterhalbjahr sinnvoll)",
    "kcal": 18,
    "fett": 0.2,
    "eiweiss": 0.9,
    "kh": 3.9,
    "vitA": 42,
    "vitC": 14,
    "vitD": 0,
    "vitE": 0.5,
    "vitK": 8.0,
    "b1": 0.04,
    "b2": 0.02,
    "niacin": 0.6,
    "b6": 0.08,
    "folat": 15,
    "b12": 0,
    "ca": 10,
    "fe": 0.3,
    "mg": 11,
    "zn": 0.2,
    "k": 240
  },
  {
    "name": "Erdbeeren (Freiland-Saison Mai–Juli)",
    "co2": 0.3,
    "season": "Mai–Juli",
    "kcal": 32,
    "fett": 0.3,
    "eiweiss": 0.7,
    "kh": 8.0,
    "vitA": 1,
    "vitC": 59,
    "vitD": 0,
    "vitE": 0.3,
    "vitK": 2.2,
    "b1": 0.02,
    "b2": 0.02,
    "niacin": 0.4,
    "b6": 0.05,
    "folat": 24,
    "b12": 0,
    "ca": 16,
    "fe": 0.4,
    "mg": 13,
    "zn": 0.1,
    "k": 150
  },
  {
    "name": "Erdbeeren (Winterware/Import)",
    "co2": 3.4,
    "season": "außerhalb Mai–Juli (Import, teils Flugware)",
    "kcal": 32,
    "fett": 0.3,
    "eiweiss": 0.7,
    "kh": 8.0,
    "vitA": 1,
    "vitC": 59,
    "vitD": 0,
    "vitE": 0.3,
    "vitK": 2.2,
    "b1": 0.02,
    "b2": 0.02,
    "niacin": 0.4,
    "b6": 0.05,
    "folat": 24,
    "b12": 0,
    "ca": 16,
    "fe": 0.4,
    "mg": 13,
    "zn": 0.1,
    "k": 150
  },
  {
    "name": "Eissalat (Freiland, Deutschland)",
    "co2": 0.6,
    "season": "ganzjährig (mit Vlies ab Mai, ohne ab Juni)",
    "kcal": 14,
    "fett": 0.1,
    "eiweiss": 0.9,
    "kh": 2.1,
    "vitA": 25,
    "vitC": 3,
    "vitD": 0,
    "vitE": 0.2,
    "vitK": 24,
    "b1": 0.05,
    "b2": 0.03,
    "niacin": 0.2,
    "b6": 0.04,
    "folat": 18,
    "b12": 0,
    "ca": 18,
    "fe": 0.4,
    "mg": 7,
    "zn": 0.2,
    "k": 140
  },
  {
    "name": "Weißkohl (Freiland, Deutschland)",
    "co2": 0.4,
    "season": "ganzjährig (Frühkohl ab Juni, sonst aus Lager)",
    "kcal": 25,
    "fett": 0.1,
    "eiweiss": 1.3,
    "kh": 4.2,
    "vitA": 1,
    "vitC": 37,
    "vitD": 0,
    "vitE": 0.1,
    "vitK": 76,
    "b1": 0.05,
    "b2": 0.04,
    "niacin": 0.3,
    "b6": 0.15,
    "folat": 43,
    "b12": 0,
    "ca": 40,
    "fe": 0.4,
    "mg": 12,
    "zn": 0.2,
    "k": 170
  },
  {
    "name": "Rindfleisch (Ackerbau-Fütterung, Regenwald-Landnutzungsänderung)",
    "co2": 21.0,
    "season": "ganzjährig (Tierhaltung)",
    "kcal": 250,
    "fett": 15,
    "eiweiss": 26,
    "kh": 0,
    "vitA": 0,
    "vitC": 0,
    "vitD": 0,
    "vitE": 0.3,
    "vitK": 1.5,
    "b1": 0.08,
    "b2": 0.2,
    "niacin": 5.0,
    "b6": 0.4,
    "folat": 6,
    "b12": 2.5,
    "ca": 12,
    "fe": 2.5,
    "mg": 22,
    "zn": 4.5,
    "k": 350
  },
  {
    "name": "Schweinefleisch (Soja-Futter, Regenwald-Landnutzungsänderung)",
    "co2": 14.0,
    "season": "ganzjährig (Tierhaltung)",
    "kcal": 242,
    "fett": 17,
    "eiweiss": 21,
    "kh": 0,
    "vitA": 2,
    "vitC": 0.5,
    "vitD": 1.0,
    "vitE": 0.3,
    "vitK": 0,
    "b1": 0.6,
    "b2": 0.2,
    "niacin": 5.0,
    "b6": 0.5,
    "folat": 3,
    "b12": 0.7,
    "ca": 10,
    "fe": 0.9,
    "mg": 20,
    "zn": 2.0,
    "k": 380
  }
];

/* ---------------- Nährstoff-Metadaten ----------------
   key muss zu einem Feld in FOODS passen. unit = wie in den Rohdaten
   hinterlegt (mg oder µg je 100g). dailyRef = DGE/D-A-CH-Referenzwert
   für Erwachsene (Richtwert, gerundet, geschlechtsunabhängiger
   Orientierungswert – siehe README für Quellen/Einschränkungen). */
const NUTRIENTS = [
  { key: "vitA",   label: "Vitamin A",   unit: "µg", dailyRef: 800 },
  { key: "vitC",   label: "Vitamin C",   unit: "mg", dailyRef: 100 },
  { key: "vitD",   label: "Vitamin D",   unit: "µg", dailyRef: 20 },
  { key: "vitE",   label: "Vitamin E",   unit: "mg", dailyRef: 12 },
  { key: "vitK",   label: "Vitamin K",   unit: "µg", dailyRef: 70 },
  { key: "b1",     label: "Vitamin B1 (Thiamin)",   unit: "mg", dailyRef: 1.1 },
  { key: "b2",     label: "Vitamin B2 (Riboflavin)", unit: "mg", dailyRef: 1.3 },
  { key: "niacin", label: "Niacin",      unit: "mg", dailyRef: 14 },
  { key: "b6",     label: "Vitamin B6",  unit: "mg", dailyRef: 1.4 },
  { key: "folat",  label: "Folat",       unit: "µg", dailyRef: 300 },
  { key: "b12",    label: "Vitamin B12", unit: "µg", dailyRef: 4.0 },
  { key: "ca",     label: "Calcium",     unit: "mg", dailyRef: 1000 },
  { key: "fe",     label: "Eisen",       unit: "mg", dailyRef: 15 },
  { key: "mg",     label: "Magnesium",   unit: "mg", dailyRef: 350 },
  { key: "zn",     label: "Zink",        unit: "mg", dailyRef: 10 },
  { key: "k",      label: "Kalium",      unit: "mg", dailyRef: 4000 },
];

const MEAL_TYPES = [
  { key: "fruehstueck", label: "Frühstück" },
  { key: "mittagessen", label: "Mittagessen" },
  { key: "abendessen",  label: "Abendessen" },
];

const DIET_MODES = [
  { key: "keine",           label: "Keine Einschränkung" },
  { key: "vegetarisch_pref",label: "Vegetarisch bevorzugt" },
  { key: "vegetarisch_nur", label: "Nur vegetarisch" },
  { key: "vegan_pref",      label: "Vegan bevorzugt" },
  { key: "vegan_nur",       label: "Nur vegan" },
];

/* Max.-Richtwerte pro Mahlzeit (grobe Ableitung aus DGE-Tagesobergrenzen
   geteilt durch 3 Mahlzeiten) — nur zur Einordnung, keine harte Grenze. */
const MEAL_MAX = { fettG: 27, zuckerG: 17, salzG: 2 };

/* Referenzwert für die "durchschnittliche Mischkost-Mahlzeit": ca. 1,7 t
   CO2e/Jahr für die Ernährung einer Person in Deutschland (Größenordnung
   nach UBA/Öko-Institut-Schätzungen), geteilt durch ca. 1.095 Mahlzeiten
   (365 Tage × 3) ≈ 1,55 kg CO2e je Mahlzeit. Grobe Orientierungsgröße,
   keine exakte Messung. */
const AVERAGE_MEAL_CO2_KG = 1.55;

/* PKW-Vergleichswert wie vom Nutzer vorgegeben. */
const CAR_G_CO2_PER_KM = 120;

/* ---------------- Abgeleitete Berechnungen ---------------- */

function co2PerKcal(food) {
  if (!food.kcal) return null;
  return (food.co2 * 1000) / (food.kcal * 10); // g CO2 je kcal
}
function co2PerGProtein(food) {
  if (!food.eiweiss) return null;
  return (food.co2 * 1000) / (food.eiweiss * 10); // g CO2 je g Eiweiß
}
function co2PerNutrientUnit(food, key) {
  const v = food[key];
  if (!v) return null;
  return (food.co2 * 1000) / (v * 10); // g CO2 je mg/µg (Einheit wie hinterlegt)
}

/* Sortierte Listen für die Dropdowns (aufsteigend nach spezifischem CO2). */
function sortedCalorieSources() {
  return FOODS.map((f) => ({ food: f, value: co2PerKcal(f) }))
    .filter((x) => x.value !== null)
    .sort((a, b) => a.value - b.value);
}
function sortedProteinSources() {
  return FOODS.map((f) => ({ food: f, value: co2PerGProtein(f) }))
    .filter((x) => x.value !== null)
    .sort((a, b) => a.value - b.value);
}
function sortedNutrientSources(key) {
  return FOODS.map((f) => ({ food: f, value: co2PerNutrientUnit(f, key) }))
    .filter((x) => x.value !== null)
    .sort((a, b) => a.value - b.value);
}

/* ---------------- Ernährungsweise-Klassifizierung ----------------
   "tierisch" = Fleisch/Fisch/Meeresfrüchte, "vegetarisch" = Ei/Milch/Käse
   (kein Fleisch/Fisch), "vegan" = alles andere. */
const ANIMAL_CATEGORY = {
  "Rindfleisch": "tierisch",
  "Rindfleisch (Ackerbau-Fütterung, Regenwald-Landnutzungsänderung)": "tierisch",
  "Lammfleisch": "tierisch",
  "Schweinefleisch": "tierisch",
  "Schweinefleisch (Soja-Futter, Regenwald-Landnutzungsänderung)": "tierisch",
  "Hähnchenfleisch": "tierisch",
  "Lachs (Zucht)": "tierisch",
  "Garnelen (Zucht)": "tierisch",
  "Eier": "vegetarisch",
  "Kuhmilch": "vegetarisch",
  "Käse (Hartkäse)": "vegetarisch",
};
function animalCategory(foodName) {
  return ANIMAL_CATEGORY[foodName] || "vegan";
}
function allowedByDiet(foodName, dietKey) {
  const cat = animalCategory(foodName);
  if (dietKey === "vegan_nur") return cat === "vegan";
  if (dietKey === "vegetarisch_nur") return cat !== "tierisch";
  return true; // "keine", "*_pref" -> Dropdown zeigt alles, Praeferenz geht als Freitext-Hinweis an DeepSeek
}
